apiVersion: v1
kind: Service
metadata:
  name: calenviroscreen
  labels:
    app: calenviroscreen
spec:
  type: ClusterIP
  selector:
    app: calenviroscreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
